#!/bin/sh
uci delete network.@device[0]

uci set network.lan_dev=device
uci set network.lan_dev.name='eth1'

uci set network.wan_dev=device
uci set network.wan_dev.name='eth0'

uci set network.lan.device='eth1'
uci set network.lan.proto='static'
uci set network.lan.ipaddr='192.168.2.253'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.ip6assign='64'
uci delete network.lan.type

uci set network.wan=interface
uci set network.wan.device='eth0'
uci set network.wan.proto='dhcp'

uci -q delete network.wan6
uci set network.wan6=interface
uci set network.wan6.device='eth0'
uci set network.wan6.proto='dhcpv6'

uci commit network
rm -f /etc/uci-defaults/99-custom-network
